#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : perl-fatpacker
Version  : 0.010008
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MS/MSTROUT/App-FatPacker-0.010008.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MS/MSTROUT/App-FatPacker-0.010008.tar.gz
Summary  : 'pack your dependencies onto your script file'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-fatpacker-bin = %{version}-%{release}
Requires: perl-fatpacker-man = %{version}-%{release}
Requires: perl-fatpacker-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
App::FatPacker - pack your dependencies onto your script file
SYNOPSIS
$ fatpack pack myscript.pl >myscript.packed.pl

%package bin
Summary: bin components for the perl-fatpacker package.
Group: Binaries

%description bin
bin components for the perl-fatpacker package.


%package dev
Summary: dev components for the perl-fatpacker package.
Group: Development
Requires: perl-fatpacker-bin = %{version}-%{release}
Provides: perl-fatpacker-devel = %{version}-%{release}
Requires: perl-fatpacker = %{version}-%{release}

%description dev
dev components for the perl-fatpacker package.


%package man
Summary: man components for the perl-fatpacker package.
Group: Default

%description man
man components for the perl-fatpacker package.


%package perl
Summary: perl components for the perl-fatpacker package.
Group: Default
Requires: perl-fatpacker = %{version}-%{release}

%description perl
perl components for the perl-fatpacker package.


%prep
%setup -q -n App-FatPacker-0.010008
cd %{_builddir}/App-FatPacker-0.010008

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fatpack

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/App::FatPacker.3
/usr/share/man/man3/App::FatPacker::Trace.3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fatpack.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.3/App/FatPacker.pm
/usr/lib/perl5/vendor_perl/5.30.3/App/FatPacker/Trace.pm
